final Map<String, List<Map<String, dynamic>>> bitc = {
  'Year One : Semester 1': [
    {'name': 'Philosophy and Current Issues', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'English for Academic Purposes', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Linear Algebra and Discrete Mathematics', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Multimedia System', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Programming Technique', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Computer Organisation and Architecture', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year One : Semester 2': [
    {'name': 'Calculus and Numerical Methods', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Human Computer Interaction', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Data Stucture and Algorithm', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Database', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Data Communication and Networking', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module I', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Two : Semester 1': [
    {'name': 'Penghayatan Etika dan Peradaban1', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Academic Writing', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Workshop I', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Statistics and Probability', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Object-oriented Programming', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Operating System', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Two : Semester 2': [
    {'name': 'Co-Curriculum I1', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Artificial Intelligence', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Software Engineering', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Wide Area Network', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Network Analysis and Design', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module II2', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Free Module III', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Three : Semester 1': [
    {'name': 'English for Professional Interaction', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Co-Curriculum II1', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Workshop II', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Network Administration and Management', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Network Project Management', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Wireless Network and Mobile Computing', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module IV', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Three : Semester 2': [
    {'name': 'Technology Entrepreneurship', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Final Year Project I', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Multimedia Networking', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Information Technology and Network Security', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'TCP/IP Programming', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module V', 'credit': 2.0, 'grade': 'N/A'},
  ],
  'Year Three : Special Semester': [
    {'name': 'Final Year Project II', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Four : Semester 1': [
    {'name': 'Industrial Training', 'credit': 6.0, 'grade': 'N/A'},
    {'name': 'Industrial Training Report', 'credit': 6.0, 'grade': 'N/A'},
  ],
};
