final Map<String, List<Map<String, dynamic>>> bitz = {
  'Year One : Semester 1': [
    {'name': 'Philosophy and Current Issues', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'English for Academic Purposes', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Co-Curriculum I', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Linear Algebra and Discrete Mathematics', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Programming Technique', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Multimedia System', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Computer Organisation and Architecture', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year One : Semester 2': [
    {'name': 'Calculus and Numerical Methods', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Human Computer Interaction', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Data Structure and Algorithm', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Database', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Data Communication and Networking', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module I', 'credit': 2.0, 'grade': 'N/A'},
  ],
  'Year Two : Semester 1': [
    {'name': 'Academic Writing', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Co-Curriculum II', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Workshop I', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Artificial Intelligence', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Statistics and Probability', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Operating System', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Computer Network', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Two : Semester 2': [
    {'name': 'Object-oriented Programming', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Software Engineering', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Network Security Infrastructure and Design', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Physical Security and Electronic Surveillance', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Cyber Law and Security Policy', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module II', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Three : Semester 1': [
    {'name': 'Penghayatan Etika dan Peradaban', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Workshop II', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Network Security Administration and Management', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Network Security Project Management', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Cryptography Application and Information Theory', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module III', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Three : Semester 2': [
    {'name': 'English for Professional Interaction', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Technology Entrepreneurship', 'credit': 2.0, 'grade': 'N/A'},
    {'name': 'Final Year Project I', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Computer Audit and Risk Management', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Hacking Techniques and Prevention', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module IV', 'credit': 3.0, 'grade': 'N/A'},
    {'name': 'Free Module V', 'credit': 2.0, 'grade': 'N/A'},
  ],
  'Year Three : Special Semester': [
    {'name': 'Final Year Project II', 'credit': 3.0, 'grade': 'N/A'},
  ],
  'Year Four : Semester 1': [
    {'name': 'Industrial Training', 'credit': 6.0, 'grade': 'N/A'},
    {'name': 'Industrial Training Report', 'credit': 6.0, 'grade': 'N/A'},
  ],
};
